#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.lyj.manage.entity
  mapperLocations: classpath:mapper/*.xml



#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://39.106.39.106:3306/mysql5.7
    username: admin
    password: admin001
    driver-class-name: com.mysql.jdbc.Driver
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource